### PR TITLE
Unit test modal component

### PR DESCRIPTION
**Pull request by vaalllaa**
This was/ is a tricky one, because this component is using 'Portals'. @mattwagl could you please have a look at the unit test of the modal component, maybe you have better ideas how the component could be picked for testing from the DOM.

### CODE REVIEW

**Comment by goloroden** [comment]
@vaalllaa I can't merge this one, since it has been marked as a draft. Is this by intention?

**Comment by goloroden** [comment]
PS: Okay, read your comment to @mattwagl 

@mattwagl From my side this is fine, then I'll leave it up to you to merge it, and re-assign.

**Comment by vaalllaa** [comment]
@mattwagl thanks for feedback! I added some more tests.

**Comment by mattwagl** [comment]
@vaalllaa Thanks for adding the additional tests. I approved your changes branch and merged the PR. We can now update thenativeweb/wolkenkit#200.

**Pull request merged**
